# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
# before:
#   hooks:
#     # You may remove this if you don't use go modules.
#     - go mod download
#     # you may remove this if you don't need go generate
#     - go generate ./...
project_name: clinvar-matcher
builds:
  - env:
    - CGO_ENABLED=0
    goos:
      - windows
      - linux
    goarch:
      - amd64
  - id: clinvar-matcher-macos
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
    hooks:
      post: gon gon.hcl
archives:
- replacements:
    darwin: OSX
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  draft: true
  extra_files:
    - glob: ./dist/clinvar-matcher-macos_darwin_amd64_signed.zip
